apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    course: devops
    trainer: "shivakumar"
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80