apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: devops
    trainer: "shivakumar"
  annotations:
    com.roboshop.training.duration: "120 HOURS"
    jenkins.url: "http://jenkins.com/roboshop/catalogue#42"
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80