apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: roboshop
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "68Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"